function getCaminhao(){
    let mySelect = document.querySelector('#mySelect');
    let selecValue = mySelect.value;

    var Volvo = ["PNEU","PREENCHIMENTO DO TACÓGRAFO","KM DE REVISÕES","MÉDIA","ARLA","TANQUE PRINCIPAL E AUXILIAR","BUJÕES DE AR","CONTROLE DE TRAÇÃO","FREIO MOTOR","PILOTO AUTOMÁTICO","CONFIGURAÇÕES DO COMPUTADOR DE BORDO","EQUIPAMENTO REBOQUE","QUINTA RODA","TRAVA E MANOBRA DO ENGATE/DESENGATE","MANGUEIRAS","DOLLY","ENLONAMENTO DA CAÇAMBA","MONTAGEM E DESMONTAGEM DO SIDER",]
    var Scania = ["PNEU","PREENCHIMENTO DO TACÓGRAFO","KM DE REVISÕES","MÉDIA","ARLA","TANQUE PRINCIPAL E AUXILIAR","BUJÕES DE AR","CONTROLE DE TRAÇÃO","FREIO MOTOR","PILOTO AUTOMÁTICO","CONFIGURAÇÕES DO COMPUTADOR DE BORDO","EQUIPAMENTO REBOQUE","QUINTA RODA","TRAVA E MANOBRA DO ENGATE/DESENGATE","MANGUEIRAS","DOLLY","BOTÃO PUSH TO SUPPLY DO SCANIA","ENLONAMENTO DA CAÇAMBA","MONTAGEM E DESMONTAGEM DO SIDER",]
    var DAF = ["PNEU","PREENCHIMENTO DO TACÓGRAFO","KM DE REVISÕES","MÉDIA","ARLA","TANQUE PRINCIPAL E AUXILIAR","BUJÕES DE AR","BOTÃO DE REGENERAÇÃO DO CATALISADOR DO DAF","CONTROLE DE TRAÇÃO","FREIO MOTOR","PILOTO AUTOMÁTICO","CONFIGURAÇÕES DO COMPUTADOR DE BORDO","EQUIPAMENTO REBOQUE","QUINTA RODA","TRAVA E MANOBRA DO ENGATE/DESENGATE","MANGUEIRAS","DOLLY","ENLONAMENTO DA CAÇAMBA","MONTAGEM E DESMONTAGEM DO SIDER",]
    var Iveco = ["PNEU","PREENCHIMENTO DO TACÓGRAFO","KM DE REVISÕES","MÉDIA","ARLA","TANQUE PRINCIPAL E AUXILIAR","BUJÕES DE AR","CONTROLE DE TRAÇÃO","FREIO MOTOR","PILOTO AUTOMÁTICO","CONFIGURAÇÕES DO COMPUTADOR DE BORDO","EQUIPAMENTO REBOQUE","QUINTA RODA","TRAVA E MANOBRA DO ENGATE/DESENGATE","MANGUEIRAS","DOLLY","ENLONAMENTO DA CAÇAMBA","MONTAGEM E DESMONTAGEM DO SIDER",]
    var MercedesBenz = ["PNEU","PREENCHIMENTO DO TACÓGRAFO","KM DE REVISÕES","MÉDIA","ARLA","TANQUE PRINCIPAL E AUXILIAR","BUJÕES DE AR","CONTROLE DE TRAÇÃO","FREIO MOTOR","PILOTO AUTOMÁTICO","CONFIGURAÇÕES DO COMPUTADOR DE BORDO","EQUIPAMENTO REBOQUE","QUINTA RODA","TRAVA E MANOBRA DO ENGATE/DESENGATE","MANGUEIRAS","DOLLY","ENLONAMENTO DA CAÇAMBA","MONTAGEM E DESMONTAGEM DO SIDER",]
    var Volkswagen = ["PNEU","PREENCHIMENTO DO TACÓGRAFO","KM DE REVISÕES","MÉDIA","ARLA","TANQUE PRINCIPAL E AUXILIAR","BUJÕES DE AR","CONTROLE DE TRAÇÃO","FREIO MOTOR","PILOTO AUTOMÁTICO","CONFIGURAÇÕES DO COMPUTADOR DE BORDO","EQUIPAMENTO REBOQUE","QUINTA RODA","TRAVA E MANOBRA DO ENGATE/DESENGATE","MANGUEIRAS","DOLLY","ENLONAMENTO DA CAÇAMBA","MONTAGEM E DESMONTAGEM DO SIDER",]
    var MAN = ["PNEU","PREENCHIMENTO DO TACÓGRAFO","KM DE REVISÕES","MÉDIA","ARLA","TANQUE PRINCIPAL E AUXILIAR","BUJÕES DE AR","CONTROLE DE TRAÇÃO","FREIO MOTOR","PILOTO AUTOMÁTICO","CONFIGURAÇÕES DO COMPUTADOR DE BORDO","EQUIPAMENTO REBOQUE","QUINTA RODA","TRAVA E MANOBRA DO ENGATE/DESENGATE","MANGUEIRAS","DOLLY","ENLONAMENTO DA CAÇAMBA","MONTAGEM E DESMONTAGEM DO SIDER",]
    
    /* IF DOS ITENS DO PDF */
    if(selecValue === 'Volvo'){
        localStorage.setItem('segmento', Volvo)
    }
    
        else if(selecValue === 'Scania'){
            localStorage.setItem('segmento', Scania)
        }

            else if(selecValue === 'DAF'){
                localStorage.setItem('segmento', DAF)
            }

                else if(selecValue === 'Iveco'){
                    localStorage.setItem('segmento', Iveco)
                }

                    else if(selecValue === 'MercedesBenz'){
                        localStorage.setItem('segmento', MercedesBenz)
                    }

                        else if(selecValue === 'Volkswagen'){
                            localStorage.setItem('segmento', Volkswagen)
                        }

                            else if(selecValue === 'MAN'){
                                localStorage.setItem('segmento', MAN)
                            }
}